--------------------------------------------------------------------------------
-- Institución : Instituto Politécnico Nacional (IPN) - UPIITA
-- Proyecto    : TX_TRASMITTER
-- Archivo     : TX_TRASMITTER.vhd
-- Descripción : Transmisor
--       PENDIENTE
--
--
-- Autor       : ARREGUÍN HERNÁNDEZ JULIO DAVID
-- Fecha       : 17/05/2026
--------------------------------------------------------------------------------



library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity TX_TRASMITTER is
    Port (  CLK : in STD_LOGIC;
		    RESET : in STD_LOGIC;
		    D : in STD_LOGIC_VECTOR(7 DOWNTO 0); -- REGISTRO PARA ENVIAR DATOS
		    SEND : in STD_LOGIC;	-- BIT PARA INICIAR EL ENVÍO DE DATOS
            --BUSSY : out STD_LOGIC:='0'; -- INDICA QUE EL BUS DE DATOS ESTÁ OCUPADO
            TX_OUT : out STD_LOGIC);-- SALIDA (BUS DE DATOS)
end TX_TRASMITTER;


architecture Behavioral of TX_TRASMITTER is
------------------------------------------------------
--			Constantes y Señales por Proceso
------------------------------------------------------
--INDICA EL NÚMERO DE CICLOS DE RELOJ QUE DEBE DURAR UN BIT SEGÚN EL BAUD RATE INDICADO:
--LO TRUNCA AL IFERIOR INMEDIATO CON MENOR ERROR DECIMAL
CONSTANT  BAUD_RATE : integer:=9600; -- TASA DE TRASMISION DE BITS POR SEGUNDO
CONSTANT N_CM_BIT_CHANGE : INTEGER:= (50_000_000+(BAUD_RATE/2))/BAUD_RATE; 
CONSTANT BIT_START_TIME : integer := 1 * N_CM_BIT_CHANGE;
CONSTANT BIT_1_TIME : integer := 2 * N_CM_BIT_CHANGE;
CONSTANT BIT_2_TIME : integer := 3 * N_CM_BIT_CHANGE;
CONSTANT BIT_3_TIME : integer := 4 * N_CM_BIT_CHANGE;
CONSTANT BIT_4_TIME : integer := 5 * N_CM_BIT_CHANGE;
CONSTANT BIT_5_TIME : integer := 6 * N_CM_BIT_CHANGE;
CONSTANT BIT_6_TIME : integer := 7 * N_CM_BIT_CHANGE;
CONSTANT BIT_7_TIME : integer := 8 * N_CM_BIT_CHANGE;
CONSTANT BIT_8_TIME : integer := 9 * N_CM_BIT_CHANGE;
CONSTANT BIT_STOP_TIME : integer := 10 * N_CM_BIT_CHANGE;

SIGNAL RESET_NOW : STD_LOGIC := '0';
SIGNAL RESET_BEFORE : STD_LOGIC := '0';

SIGNAL SEND_NOW : STD_LOGIC := '0';
SIGNAL SEND_BEFORE : STD_LOGIC := '0';

SIGNAL TX_SIGNAL : STD_LOGIC := '1'; --LA LOGICA DE ESTE BIT ES INVERSA
SIGNAL BUSSY_SIGNAL : STD_LOGIC := '0';

SIGNAL CLK_CONT : INTEGER := 0;


begin

TX_SEND : PROCESS(CLK)
begin
	IF RISING_EDGE(CLK) THEN
	--ACTUALIZAMOS FFP DE RESET:
	RESET_BEFORE <= RESET_NOW;
	RESET_NOW <= RESET;

	--ACTUALIZAMOS FFP DE RESET:
	SEND_BEFORE <= SEND_NOW;
	SEND_NOW <= SEND;

	

	--EVALUAMOS SI SE ORDENÓ UN RESET:
		IF RESET_BEFORE = '0' AND RESET_NOW = '1' THEN
		--DEVOLVER TODO A SU ESTADO INICIAL:
		NULL;
		
	--EVALUAMOS SI SE ORDENÓ INICIAR LA TRASMISION DE UN MENSAJE:	
		ELSIF SEND_BEFORE = '0' AND SEND_NOW = '1' AND BUSSY_SIGNAL = '0' THEN
		BUSSY_SIGNAL <= '1'; 			--INDICAMOS QUE EL BUS SE ENCUENTRA OCUPADO
		TX_SIGNAL <= '0'; 	--DAR EL BIT DE INICIO
		CLK_CONT <= 0; --RE-INICIAMOS EL CONTADOR;
		
	

	--EVALUAMOS SI SE ENCUENTRA ENVIANDO DATOS:
		ELSIF BUSSY_SIGNAL <= '1' THEN
		--EMPEZAMOS A CONTAR EL NÚMERO DE CICLOS DE RELOJ TRANCURRIDOS:
		CLK_CONT <= CLK_CONT + 1;
		--EVALUAMOS EN QUÉ PUNTO DEL TIEMPO NOS ENCONTRAMOS:
		CASE CLK_CONT IS
		
			--ENVIANDO EL BIT "START". DE 0 A 1*N_CM_BIT_CHANGE:
			
			WHEN BIT_START_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--ENVIANDO EL BIT D(0) DE BIT_START_TIME A BIT_1_TIME:
			TX_SIGNAL <= D(0);
			
			WHEN BIT_1_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--ENVIANDO EL BIT D(1) DE BIT_1_TIME A BIT_2_TIME:
			TX_SIGNAL <= D(1);
			
			WHEN BIT_2_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--ENVIANDO EL BIT D(2) DE BIT_2_TIME A BIT_3_TIME:
			TX_SIGNAL <= D(2);
			
			WHEN BIT_3_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--ENVIANDO EL BIT D(3) DE BIT_3_TIME A BIT_4_TIME:
			TX_SIGNAL <= D(3);
			
			WHEN BIT_4_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--ENVIANDO EL BIT D(4) DE BIT_4_TIME A BIT_5_TIME:
			TX_SIGNAL <= D(4);
			
			WHEN BIT_5_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--ENVIANDO EL BIT D(5) DE BIT_5_TIME A BIT_6_TIME:
			TX_SIGNAL <= D(5);
			
			WHEN BIT_6_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--ENVIANDO EL BIT D(6) DE BIT_6_TIME A BIT_7_TIME:
			TX_SIGNAL <= D(6);
			
			WHEN BIT_7_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--ENVIANDO EL BIT D(7) DE BIT_7_TIME A BIT_STOP_TIME:
			TX_SIGNAL <= D(7);

			WHEN BIT_8_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--COMO NO USAMOS EL BIT DE PARIDAD SIMPLEMENTE:
			TX_SIGNAL <= '1';

			WHEN BIT_STOP_TIME => --AL TÉRMINO DE ESTE ENVIO:
			--ENVIANDO EL BIT "STOP" EN CUANTO CLK_CONT = BIT_STOP_TIME:
			--TX_SIGNAL <= '1';
			--INDICAMOS QUE EL BUS SE ENCUENTRA DESOCUPADO:
			BUSSY_SIGNAL <= '0';
 			
			WHEN OTHERS =>
			NULL;
		END CASE;

	--SIN CAMBIOS IMPORTANTES:
		ELSE
		NULL;
		
		END IF;
	END IF;
END PROCESS;
-- ASIGNACIONES DIRECTAS ASOCIADAS:
TX_OUT <= TX_SIGNAL;
--BUSSY <= BUSSY_SIGNAL;


end Behavioral;